---
openapi: 3.0.0
info:
  title: TMDB Web App API
  description: |
    Ben Capper (20088114) - Web App API.
  contact:
    email: 20088114@mail.wit.ie
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/BENCAPPER19/movies/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: Movies
- name: Tv
- name: Users
- name: Genres
- name: Search
- name: Company
paths:
  /movies:
    get:
      tags:
      - Movies
      summary: Return a list of movies
      description: Return a list of movies
      operationId: getMovies
      responses:
        "200":
          description: Movies successfully returned
  /movies/{movieId}:
    get:
      tags:
      - Movies
      summary: Return a movie by ID
      description: Returns a single movie
      operationId: getMovieById
      parameters:
      - name: movieId
        in: path
        description: ID of movie to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int
      responses:
        "200":
          description: Movie successfully returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
            application/xml:
              schema:
                $ref: '#/components/schemas/Movie'
        "400":
          description: Invalid ID supplied
        "404":
          description: Movie not found
  /movies/{movieId}/similar:
    get:
      tags:
      - Movies
      summary: Return a list similar movies
      description: Returns a list of similar movies
      operationId: getSimilarMovies
      parameters:
      - name: movieId
        in: path
        description: ID of movie to find similar movies to
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int
      responses:
        "200":
          description: Similar movies successfully returned
        "400":
          description: Invalid ID supplied
        "404":
          description: Similar movies not found
  /movies/{movieId}/images:
    get:
      tags:
      - Movies
      summary: Return a list of movie images
      description: Returns a list of movie images
      operationId: getMovieImages
      parameters:
      - name: movieId
        in: path
        description: ID of movie to find images of
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int
      responses:
        "200":
          description: Movie Images successfully returned
        "400":
          description: Invalid ID supplied
        "404":
          description: Images not found
  /movies/{movieId}/reviews:
    get:
      tags:
      - Movies
      summary: Return a list of movie reviews
      description: Returns a list of movie reviews
      operationId: getMovieReviews
      parameters:
      - name: movieId
        in: path
        description: ID of movie to find reviews of
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int
      responses:
        "200":
          description: Movie reviews successfully returned
        "400":
          description: Invalid ID supplied
        "404":
          description: Reviews not found
  /movies/tmdb/upcoming:
    get:
      tags:
      - Movies
      summary: Return a list of upcoming movies
      description: Returns a list of upcoming movies
      operationId: getUpcomingMovies
      responses:
        "200":
          description: Upcoming movies successfully returned
        "404":
          description: Upcoming movies not found
  /movies/tmdb/trending:
    get:
      tags:
      - Movies
      summary: Return a list of trending movies
      description: Returns a list of trending movies
      operationId: getTrendingMovies
      responses:
        "200":
          description: Trending movies successfully returned
        "404":
          description: Trending movies not found
  /tv:
    get:
      tags:
      - Tv
      summary: Return a list of tv series
      description: Return a list of tv series
      operationId: getTv
      responses:
        "200":
          description: Tv successfully returned
  /tv/{tvId}:
    get:
      tags:
      - Tv
      summary: Return a tv series by ID
      description: Returns a single tv series
      operationId: getTvById
      parameters:
      - name: tvId
        in: path
        description: ID of tv series to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int
      responses:
        "200":
          description: Tv series successfully returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
            application/xml:
              schema:
                $ref: '#/components/schemas/Movie'
        "400":
          description: Invalid ID supplied
        "404":
          description: Tv series not found
  /tv/{tvId}/images:
    get:
      tags:
      - Tv
      summary: Return a list of tv series images
      description: Returns a list of tv series images
      operationId: getTvImages
      parameters:
      - name: tvId
        in: path
        description: ID of tv series to find images of
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int
      responses:
        "200":
          description: Images successfully returned
        "400":
          description: Invalid ID supplied
        "404":
          description: Images not found
  /tv/{tvId}/reviews:
    get:
      tags:
      - Tv
      summary: Return a list of tv series reviews
      description: Returns a list of tv series reviews
      operationId: getTvReviews
      parameters:
      - name: tvId
        in: path
        description: ID of tv series to find reviews of
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int
      responses:
        "200":
          description: Tv series reviews successfully returned
        "400":
          description: Invalid ID supplied
        "404":
          description: Reviews not found
  /tv/{tvId}/season/{seasonId}:
    get:
      tags:
      - Tv
      summary: Return a season of a tv series
      description: Returns a season of a tv series
      operationId: getTvSeason
      parameters:
      - name: tvId
        in: path
        description: ID of tv series to find a season of
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int
      - name: seasonId
        in: path
        description: ID of season of the tv series to find.
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int
      responses:
        "200":
          description: Tv season successfully returned
        "400":
          description: Invalid ID supplied
        "404":
          description: Tv season not found
  /tv/tmdb/top:
    get:
      tags:
      - Tv
      summary: Return a list of upcoming movies
      description: Returns a list of upcoming movies
      operationId: getUpcomingTv
      responses:
        "200":
          description: Upcoming movies successfully returned
        "404":
          description: Upcoming movies not found
  /tv/tmdb/trending:
    get:
      tags:
      - Tv
      summary: Return a list of trending movies
      description: Returns a list of trending movies
      operationId: getTrendingTv
      responses:
        "200":
          description: Trending movies successfully returned
        "404":
          description: Trending movies not found
  /users:
    get:
      tags:
      - Users
      summary: Return the list of users
      description: Return the list of users
      operationId: getUsers
      responses:
        "200":
          description: Users successfully returned
    post:
      tags:
      - Users
      summary: Register a user
      description: Register a user
      operationId: registerUser
      responses:
        "200":
          description: User successfully returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
            application/xml:
              schema:
                $ref: '#/components/schemas/Movie'
        "400":
          description: Invalid ID supplied
        "404":
          description: Tv series not found
  /users/{userId}:
    put:
      tags:
      - Users
      summary: Update a user
      description: Update a user
      operationId: updateUser
      parameters:
      - name: userId
        in: path
        description: ID of user to be updated
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int
      responses:
        "200":
          description: User successfully updated
  /users/{username}/favourites/movies:
    get:
      tags:
      - Users
      summary: Return a list of the users favourite movies
      description: Return a list of the users favourite movies
      operationId: getUsersFavouriteMovies
      parameters:
      - name: username
        in: path
        description: username of user whose favourites are returned
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: str
      responses:
        "200":
          description: Users favourite movies successfully returned
    post:
      tags:
      - Users
      summary: Add a movie to a users favourites
      description: Add a movie to a users favourites
      operationId: addUsersFavouriteMovie
      parameters:
      - name: username
        in: path
        description: username of user whose favourites are returned
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: str
      responses:
        "200":
          description: Favourite movie successfully added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
            application/xml:
              schema:
                $ref: '#/components/schemas/Movie'
        "400":
          description: Invalid username supplied
        "404":
          description: Movie not added to favourites
  /users/{username}/favourites/tv:
    get:
      tags:
      - Users
      summary: Return a list of the users favourite tv series
      description: Return a list of the users favourite tv series
      operationId: getUsersFavouriteTv
      parameters:
      - name: username
        in: path
        description: username of user whose favourites are returned
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: str
      responses:
        "200":
          description: Users favourite tv series successfully returned
    post:
      tags:
      - Users
      summary: Add a tv series to a users favourites
      description: Add a tv series to a users favourites
      operationId: addUsersFavouriteTv
      parameters:
      - name: username
        in: path
        description: username of user whose favourites are returned
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: str
      responses:
        "200":
          description: Favourite tv series successfully added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
            application/xml:
              schema:
                $ref: '#/components/schemas/Movie'
        "400":
          description: Invalid username supplied
        "404":
          description: Tv series not added to favourites
  /genres:
    get:
      tags:
      - Genres
      summary: Return a list of genres
      description: Return a list of genres
      operationId: getGenres
      responses:
        "200":
          description: Genres successfully returned
  /genres/{genreId}:
    put:
      tags:
      - Genres
      summary: Update a genre
      description: Update a genre
      operationId: updateGenre
      parameters:
      - name: genreId
        in: path
        description: ID of genre to be updated
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int
      responses:
        "200":
          description: User successfully updated
  /genres/tv:
    get:
      tags:
      - Genres
      summary: Return the list of tv genres
      description: Return the list of tv genres
      operationId: getTvGenres
      responses:
        "200":
          description: Genres successfully returned
  /genres/movie:
    get:
      tags:
      - Genres
      summary: Return the list of movie genres
      description: Return the list of movie genres
      operationId: getMovieGenres
      responses:
        "200":
          description: Genres successfully returned
  /search/company/{query}:
    get:
      tags:
      - Search
      summary: Return a list of companies
      description: Return a list of companies matching the query
      operationId: searchCompanies
      parameters:
      - name: query
        in: path
        description: Search term to match results against
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: str
      responses:
        "200":
          description: Companies successfully returned
  /search/person/{query}:
    get:
      tags:
      - Search
      summary: Return a list of people
      description: Return a list of people matching the query
      operationId: searchPeople
      parameters:
      - name: query
        in: path
        description: Search term to match results against
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: str
      responses:
        "200":
          description: People successfully returned
  /company/{companyId}:
    get:
      tags:
      - Company
      summary: Return a production company
      description: Return a production company
      operationId: getProductionCompany
      parameters:
      - name: companyId
        in: path
        description: Id of production company to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int
      responses:
        "200":
          description: Production company successfully returned
components:
  schemas:
    Movie:
      type: object
      properties:
        id:
          type: integer
          format: int
        adult:
          type: boolean
          format: bool
        poster_path:
          type: string
          format: str
        overview:
          type: string
          format: str
        release_date:
          type: string
          format: str
        original_title:
          type: string
          format: str
        genre_ids:
          type: array
          items:
            type: integer
            format: int
        original_language:
          type: string
          format: str
        title:
          type: string
          format: str
        backdrop_path:
          type: string
          format: str
        popularity:
          type: integer
          format: int
        vote_count:
          type: integer
          format: int
        video:
          type: boolean
          format: bool
        vote_average:
          type: integer
          format: int
        production_countries:
          type: array
          items:
            xml:
              name: iso_3166_1
        runtime:
          type: integer
          format: int
        status:
          type: string
          format: str
        tagline:
          type: string
          format: str
    Tv:
      type: object
      properties:
        id:
          type: integer
          format: int
        backdrop_path:
          type: string
          format: str
        favorite:
          type: boolean
          format: bool
        genre_ids:
          type: array
          items:
            type: integer
            format: int
        mustWatch:
          type: boolean
          format: bool
        name:
          type: string
          format: str
        origin_country:
          type: array
          items:
            type: string
            format: str
        original_language:
          type: string
          format: str
        original_name:
          type: string
          format: str
        overview:
          type: string
          format: str
        popularity:
          type: integer
          format: int
        vote_count:
          type: integer
          format: int
        poster_path:
          type: boolean
          format: bool
        vote_average:
          type: integer
          format: int
    Users:
      type: object
      properties:
        username:
          type: string
          format: str
        password:
          type: string
          format: str
        favouriteMovies:
          type: array
          items:
            $ref: '#/components/schemas/Movie'
        favouriteTv:
          type: array
          items:
            $ref: '#/components/schemas/Tv'
    Genres:
      type: object
      properties:
        id:
          type: integer
          format: int
        name:
          type: string
          format: str
